version: 2
jobs:
  build:
    working_directory: /tmp/workspace
    docker:
     - image: circleci/golang
    steps:
      - checkout
      - restore_cache:
         keys:
           - ci_test-{{ checksum "go.mod" }}
      - run: go build
      - setup_remote_docker
      - run: docker build -t mehryaar/testserver -f /tmp/workspace/.circleci/Dockerfile /tmp/workspace/
      - run: docker save mehryaar/testserver > testserver.tar
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - testserver.tar
      - save_cache:
          key: ci_test-{{ checksum "go.mod" }}
          paths:
            - "/go/pkg/mod/"
  
  push:
    docker:
     - image: circleci/golang
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run: docker load <  /tmp/workspace/testserver.tar
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker push mehryaar/testserver
  
  test:
    docker:
     - image: foodora/golang
    steps:
      - checkout
      - restore_cache:
         keys:
           - ci_test-{{ checksum "go.mod" }}
      - run: go vet
      - run: go test
      - run: go build
      - setup_remote_docker
      - run:
          name: build source image to run tests from
          command: |
            docker run -d --name src-data golang sleep infinity
            docker exec -d src-data mkdir -p /go/pkg /build
            docker cp . src-data:/build
            cp -r /go/pkg/mod .
            docker cp /go/pkg/mod src-data:/go/pkg/mod
            docker commit src-data src-img
      - run: docker-compose -f .circleci/docker-compose.yml up -d
      - run: docker-compose -f .circleci/docker-compose.yml run src go test -tags integration -v
 
  report:
    docker:
     - image: mehryaar/runner_sloc
    steps:
      - checkout
      - run: /go/bin/sloc .

workflows:
  version: 2
  all:
    jobs:
      - test
      - report
      - build
      - push:
          context: tokens
          requires:
            - test
            - build

