version: 2
jobs:
  build:
    working_directory: /tmp/workspace
    docker:
     - image: circleci/golang
    steps:
      - checkout
      - restore_cache:
         keys:
           - ci_test_{{ checksum "go.mod" }}
      - run: mkdir -p ~/gopath
      - run: GOPATH=~/gopath go build
      - setup_remote_docker
      - run: docker build -t mehryaar/testserver -f /tmp/workspace/.circleci/Dockerfile /tmp/workspace/
      - run: docker save mehryaar/testserver > testserver.tar
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - testserver.tar
      - save_cache:
          key: ci_test_{{ checksum "go.mod" }}
          paths:
            - "~/gopath"
  
  test:
    machine:
      image: circleci/classic:201808-01
    steps:
      - run: sudo rm -Rf /usr/local/go && sudo circleci-install golang 1.11
      - checkout
      - restore_cache:
         keys:
           - ci_test_{{ checksum "go.mod" }}
      - run: GOPATH=~/gopath go test -v
      # run integration tests
      - run: docker-compose -f .circleci/docker-compose.yml up -d
      - run: GOPATH=~/gopath go test -tags integration -v

  push:
    docker:
     - image: circleci/golang
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run: docker load <  /tmp/workspace/testserver.tar
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker push mehryaar/testserver
 
  analyze:
    docker:
     - image: mehryaar/go-analyze
    steps:
      - checkout
      - run: go-analyze.sh .

workflows:
  version: 2
  all:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - analyze:
          filters:
            tags:
              only: /.*/
            branches:
              only:
                - master
      - build:
          filters:
            tags:
              only: /.*/
      - push:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
          context: tokens
          requires:
            - test

