version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
  app:
    build:
      context: ../
      dockerfile: .circleci/Dockerfile
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      - db
  # src:
  #   image: src-img
  #   environment:
  #     POSTGRES_HOST: db
  #     POSTGRES_DB: test
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     APP_URL: app
  #   depends_on:
  #     - db
  #     - app